use_frameworks!

platform :ios, '8.0'

target 'GCAssistWindow_Example' do
  pod 'GCAssistWindow', :path => '../'

  target 'GCAssistWindow_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
